name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang, msvc]

    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          if [ "$RUNNER_OS" = "Windows" ]; then
            .\\vcpkg\\bootstrap-vcpkg.bat
          else
            ./vcpkg/bootstrap-vcpkg.sh
          fi
        shell: bash
      - name: Configure CMake
        run: cmake --preset ninja-release
      - name: Build
        run: cmake --build --preset ninja-release
      - name: Run Tests
        run: cmake --build --preset ninja-release --target test
      - name: Run clang-format check
        run: |
          git diff --exit-code -- . ':(exclude)**/.github/**'
